version: '3'
services:
  db:
    image: mysql
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - web
