version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - web
